modLoader = "javafml"
license = "LGPL 2.1"
issueTrackerURL = "https://github.com/Darkhax-Minecraft/Tip-of-the-Loom/issues"

[[mods]]
modId = "tipoftheloom"
version = "26.1.2.0"
displayName = "TipOfTheLoom"
updateJSONURL = "https://updates.blamejared.com/get?n=tipoftheloom&gv=26.1.2&ml=neoforge"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/tip-of-the-loom"
logoFile = "logo_tipoftheloom.png"
logoBlur = false
credits = "This project is made possible with Patreon support from players like you. Thank you! lothrazar, techsquirrel, Keyana , Darkosto, Tobias Ward, noobanidus"
authors = "Darkhax"
description = "Adds tooltips to banner pattern buttons in the loom."

[[mixins]]
config = "tipoftheloom.common.mixins.json"

[[mixins]]
config = "tipoftheloom.neoforge.mixins.json"

[[dependencies.tipoftheloom]]
modId = "minecraft"
type = "required"
versionRange = "26.1"
ordering = "NONE"
side = "BOTH"

[[dependencies.tipoftheloom]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.0.1-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tipoftheloom]]
modId = "bookshelf"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tipoftheloom]]
modId = "prickle"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

